name: local-build
on:
  workflow_dispatch: {} 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build all images (no push)
        run: |
          docker build -t task-platform-backend:v2.0.0-vibe backend
          docker build -t task-platform-frontend:v2.0.0-vibe frontend
          docker build -t task-platform-worker:v2.0.0-vibe worker
